[build]
  publish = "public"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "22"
  NPM_VERSION = "10"

# Function routing - Critical for API endpoints
[[redirects]]
  from = "/api/process-payment"
  to = "/.netlify/functions/process-payment"
  status = 200
  force = true

[[redirects]]
  from = "/api/calculate-price"
  to = "/.netlify/functions/calculate-price"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Buy page routing (must come after API routes)
[[redirects]]
  from = "/buy/*"
  to = "/index.html"
  status = 200

# Catch-all for SPA routing (last priority)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers for functions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://buy.mountainshares.us"
    Access-Control-Allow-Methods = "POST, GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"

# Security headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
